
export const ON_LOGIN_START = 'ON_LOGIN_START';
export const ON_LOGIN_SUCCESS = 'ON_LOGIN_SUCCESS';
export const ON_LOGIN_FAILED = 'ON_LOGIN_FAILED';
export const ON_RESET_ERROR = 'ON_RESET_ERROR';

export const ON_LOGOUT = 'ON_LOGOUT';

export const NEWS_RESET = 'NEWS_RESET';

export const NEWS_FETCH_START = 'NEWS_FETCH_START';
export const NEWS_FETCH_SUCCESS = 'NEWS_FETCH_SUCCESS';
export const NEWS_FETCH_FAILED = 'NEWS_FETCH_FAILED';

export const NEWS_TOP_HEADLINE_SUCESS= 'NEWS_TOP_HEADLINE_SUCESS';
export const NEWS_TOP_HEADLINE_START = 'NEWS_TOP_HEADLINE_START';
export const NEWS_TOP_HEADLINE_FAILED = 'NEWS_TOP_HEADLINE_FAILED';

export const NEWS_SOURCE_FETCH_START = 'NEWS_SOURCE_FETCH_START';
export const NEWS_SOURCE_FETCH_SUCCESS = 'NEWS_SOURCE_FETCH_SUCCESS';
export const NEWS_SOURCE_FETCH_FAILED = 'NEWS_SOURCE_FETCH_FAILED';

export const COUNTRY_FETCH_START = 'COUNTRY_FETCH_START';
export const COUNTRY_FETCH_FAILED = 'COUNTRY_FETCH_FAILED';
export const COUNTRY_FETCH_SUCCESS= 'OUNTRY_FETCH_SUCCESS';
