export const ON_LOGIN = 'ON_LOGIN';
export const ON_LOGOUT = 'ON_LOGOUT';

export const NEWS_FETCH_START = 'NEWS_FETCH_START';
export const NEWS_FETCH_SUCCESS = 'NEWS_FETCH_SUCCESS';
export const NEWS_FETCH_FAILED = 'NEWS_FETCH_FAILED';


export const NEWS_SOURCE_FETCH_START = 'NEWS_SOURCE_FETCH_START';
export const NEWS_SOURCE_FETCH_SUCCESS = 'NEWS_SOURCE_FETCH_SUCCESS';
export const NEWS_SOURCE_FETCH_FAILED = 'NEWS_SOURCE_FETCH_FAILED';

export const COUNTRY_FETCH_START = 'COUNTRY_FETCH_START';
export const COUNTRY_FETCH_FAILED = 'COUNTRY_FETCH_FAILED';
export const COUNTRY_FETCH_SUCCESS= 'OUNTRY_FETCH_SUCCESS';
